#define NEGXBOUNDS -1.5
#define POSXBOUNDS 1.5
#define NEGZBOUNDS -2.5
#define POSZBOUNDS 2.5

#define SODACANSCALEX 0.25f
#define SODACANSCALEY 0.25f
#define SODACANSCALEZ 0.25f

#define SODACANLOCATX 0.0f
#define SODACANLOCATY 2.35f
#define SODACANLOCATZ 1.0f

#define NUMBLINDS 15
#define BLINDSHFTVAL 0.1f

#define FANLOCATX 0.0f
#define FANLOCATY 2.0f
#define FANLOCATZ 0.0f

#define FANSWITCHTHETA 45.0
#define LIGHTSWITCHTHETA 45.0

#define CHAIR1LOCATX 0.0f
#define CHAIR1LOCATY 0.5f
#define CHAIR1LOCATZ 0.75f

#define CHAIR2LOCATX 0.75f
#define CHAIR2LOCATY 0.5f
#define CHAIR2LOCATZ 0.0f

#define CHAIR3LOCATX 0.0f
#define CHAIR3LOCATY 0.5f
#define CHAIR3LOCATZ -0.75f

#define CHAIR4LOCATX -0.75f
#define CHAIR4LOCATY 0.5f
#define CHAIR4LOCATZ 0.0f

#define LEFTWALLSCALEX 0.25f
#define LEFTWALLSCALEY 2.5f
#define LEFTWALLSCALEZ 8.0f

#define LEFTWALLLOCATX 8.0f
#define LEFTWALLLOCATY 0.5f
#define LEFTWALLLOCATZ 0.0f

#define RIGHTWALLSCALEX 0.25f
#define RIGHTWALLSCALEY 2.5f
#define RIGHTWALLSCALEZ 8.0f

#define RIGHTWALLLOCATX -8.0f
#define RIGHTWALLLOCATY 0.5f
#define RIGHTWALLLOCATZ 0.0f

#define FRONTWALLSCALEX 6.0f
#define FRONTWALLSCALEY 2.5f
#define FRONTWALLSCALEZ 0.25f

#define FRONTWALLLOCATX 0.0f
#define FRONTWALLLOCATY 0.5f
#define FRONTWALLLOCATZ 12.0f

#define BACKWALLSCALEX 6.0f
#define BACKWALLSCALEY 2.5f
#define BACKWALLSCALEZ 0.25f

#define BACKWALLLOCATX 0.0f
#define BACKWALLLOCATY 0.5f
#define BACKWALLLOCATZ -12.0f

#define CEILINGSCALEX 4.0f
#define CEILINGSCALEY 0.15f
#define CEILINGSCALEZ 6.0f

#define CEILINGLOCATX 0.0f
#define CEILINGLOCATY 15.0f
#define CEILINGLOCATZ 0.0f

#define FLOORSCALEX 4.0f
#define FLOORSCALEY 0.0f
#define FLOORSCALEZ 6.0f

#define TABLETOPSCALEX 0.5f
#define TABLETOPSCALEY 0.1f
#define TABLETOPSCALEZ 0.5f

#define TABLETOPSHADOWSCALEX 0.6f
#define TABLETOPSHADOWSCALEY 0.1f
#define TABLETOPSHADOWSCALEZ 0.6f

#define TABLETOPLOCATX 0.0f
#define TABLETOPLOCATY 5.0f
#define TABLETOPLOCATZ 0.0f

#define TABLELEGSCALEX 0.1f
#define TABLELEGSCALEY 0.55f
#define TABLELEGSCALEZ 0.1f

#define TABLELEGLOCATX 3.0f
#define TABLELEGLOCATY 0.5f
#define TABLELEGLOCATZ 3.0f

#define CHAIRBOTTOMSCALEX 0.3f
#define CHAIRBOTTOMSCALEY 0.05f
#define CHAIRBOTTOMSCALEZ 0.3f

#define CHAIRBOTTOMLOCATX 0.0f
#define CHAIRBOTTOMLOCATY -3.25f
#define CHAIRBOTTOMLOCATZ 0.0f

#define CHAIRLEGSCALEX 0.05f
#define CHAIRLEGSCALEY 0.3f
#define CHAIRLEGSCALEZ 0.05f

#define CHAIRLEGLOCATX 2.5f
#define CHAIRLEGLOCATY -1.1f
#define CHAIRLEGLOCATZ 2.5f

#define CHAIRBACKSCALEX 0.3f
#define CHAIRBACKSCALEY 0.3f
#define CHAIRBACKSCALEZ 0.05f

#define CHAIRBACKLOCATX 0.0f
#define CHAIRBACKLOCATY 0.0f
#define CHAIRBACKLOCATZ 2.5f

#define CEILINGFANLIGHTSCALEX 0.1f
#define CEILINGFANLIGHTSCALEY 0.1f
#define CEILINGFANLIGHTSCALEZ 0.1f

#define CEILINGFANBLADESCALE1X 0.01f
#define CEILINGFANBLADESCALE1Y 0.5f
#define CEILINGFANBLADESCALE1Z 0.1f

#define CEILINGFANBLADESCALE2X 0.1f
#define CEILINGFANBLADESCALE2Y 0.5f
#define CEILINGFANBLADESCALE2Z 0.01f

#define CEILINGFANBLADE1LOCATX 0.25f
#define CEILINGFANBLADE1LOCATY 0.0f
#define CEILINGFANBLADE1LOCATZ 0.0f

#define CEILINGFANBLADE2LOCATX 0.0f
#define CEILINGFANBLADE2LOCATY 0.0f
#define CEILINGFANBLADE2LOCATZ 0.25f

#define CEILINGFANBLADE3LOCATX -0.25f
#define CEILINGFANBLADE3LOCATY 0.0f
#define CEILINGFANBLADE3LOCATZ 0.0f

#define CEILINGFANBLADE4LOCATX 0.0f
#define CEILINGFANBLADE4LOCATY 0.0f
#define CEILINGFANBLADE4LOCATZ -0.25f

#define CEILINGFANCONNECTSCALEX 0.05f
#define CEILINGFANCONNECTSCALEY 0.3f
#define CEILINGFANCONNECTSCALEZ 0.05f

#define CEILINGFANCONNECTLOCATX 0.0f
#define CEILINGFANCONNECTLOCATY 0.2f
#define CEILINGFANCONNECTLOCATZ 0.0f

#define GLASSWITHSODASCALEX 0.25f
#define GLASSWITHSODASCALEY 0.25f
#define GLASSWITHSODASCALEZ 0.25f

#define GLASSWITHSODALOCATX -1.0f
#define GLASSWITHSODALOCATY 2.5f
#define GLASSWITHSODALOCATZ 0.0f

#define SWITCHLOCATX 0.5f
#define SWITCHLOCATY 0.0f
#define SWITCHLOCATZ 2.75f

#define SWITCHBLOCKSCALEX 0.2f
#define SWITCHBLOCKSCALEY 0.2f
#define SWITCHBLOCKSCALEZ 0.1f

#define SWITCHBLOCKLOCATX 0.0f
#define SWITCHBLOCKLOCATY 4.0f
#define SWITCHBLOCKLOCATZ 0.0f

#define SWITCHSCALEX 0.05f
#define SWITCHSCALEY 0.05f
#define SWITCHSCALEZ 0.1f

#define LIGHTSWITCHLOCATX 0.05f
#define LIGHTSWITCHLOCATY 0.8f
#define LIGHTSWITCHLOCATZ 0.0f

#define FANSWITCHLOCATX -0.05f
#define FANSWITCHLOCATY 0.8f
#define FANSWITCHLOCATZ 0.0f

#define DOORSCALEX 0.3f
#define DOORSCALEY 0.6f
#define DOORSCALEZ 0.3f

#define DOORLOCATX 0.0f
#define DOORLOCATY 0.6f
#define DOORLOCATZ 3.045f

#define WINDOWSCALEX 0.75f
#define WINDOWSCALEY 0.5f
#define WINDOWSCALEZ 0.1f

#define WINDOWLOCATX 1.84f
#define WINDOWLOCATY 1.5f
#define WINDOWLOCATZ 1.0f

#define BOWLBASESCALEX 0.15f
#define BOWLBASESCALEY 0.2f
#define BOWLBASESCALEZ 0.15f

#define BOWLSIDESCALEX 0.15f
#define BOWLSIDESCALEY 0.15f
#define BOWLSIDESCALEZ 0.15f

#define BOWLLOCATX 0.0f
#define BOWLLOCATY 0.65f
#define BOWLLOCATZ -0.25f

#define FRUITSCALEX 0.05f
#define FRUITSCALEY 0.05f
#define FRUITSCALEZ 0.05f

#define FRUITLOCATX 0.0f
#define FRUITLOCATY 0.7f
#define FRUITLOCATZ -0.25f

#define BLINDSCALEX 0.05f
#define BLINDSCALEY 0.9f
#define BLINDSCALEZ 0.05f

#define BLINDLOCATX 1.72f
#define BLINDLOCATY 1.5f
#define BLINDLOCATZ 0.2f

#define ARTSCALEX 1.0f
#define ARTSCALEY 0.5f
#define ARTSCALEZ 0.1f

#define ARTLOCATX 0.0f
#define ARTLOCATY 1.0f
#define ARTLOCATZ -2.845f
